//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:34:30 AM CAT 
//


package auto.softserve.XMLEntities.CV;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conferencesWorkshopsCourses" type="{}item"/>
 *         &lt;element name="teamworkCollaboration" type="{}item"/>
 *         &lt;element name="memberships" type="{}item"/>
 *         &lt;element name="vistsToInsitutions" type="{}item"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conferencesWorkshopsCourses",
    "teamworkCollaboration",
    "memberships",
    "vistsToInsitutions"
})
@XmlRootElement(name = "otherContributions")
public class OtherContributions {

    @XmlElement(required = true)
    protected Item conferencesWorkshopsCourses;
    @XmlElement(required = true)
    protected Item teamworkCollaboration;
    @XmlElement(required = true)
    protected Item memberships;
    @XmlElement(required = true)
    protected Item vistsToInsitutions;

    /**
     * Gets the value of the conferencesWorkshopsCourses property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getConferencesWorkshopsCourses() {
        return conferencesWorkshopsCourses;
    }

    /**
     * Sets the value of the conferencesWorkshopsCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setConferencesWorkshopsCourses(Item value) {
        this.conferencesWorkshopsCourses = value;
    }

    /**
     * Gets the value of the teamworkCollaboration property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getTeamworkCollaboration() {
        return teamworkCollaboration;
    }

    /**
     * Sets the value of the teamworkCollaboration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setTeamworkCollaboration(Item value) {
        this.teamworkCollaboration = value;
    }

    /**
     * Gets the value of the memberships property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getMemberships() {
        return memberships;
    }

    /**
     * Sets the value of the memberships property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setMemberships(Item value) {
        this.memberships = value;
    }

    /**
     * Gets the value of the vistsToInsitutions property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getVistsToInsitutions() {
        return vistsToInsitutions;
    }

    /**
     * Sets the value of the vistsToInsitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setVistsToInsitutions(Item value) {
        this.vistsToInsitutions = value;
    }

}
